### ISSUE TITLE
Binance Futures - multiples order same pair

### ISSUE THREAD

**Issue by evanherve** [Haehnchen/crypto-trading-bot#120] opened 2020-04-26 13:11 UTC
My indicator is creating buy / short signals and they are sent everytime to the createOrder method of binance_futures.js.

I think it does that because before each call it checks if there are current open positions for each pair and the current method getPositions() in binance_futures always returns an empty Object.

To resolve this issue I had to add this.syncPositionViaRestApi(); call to

```
async getPositions() {
    this.syncPositionViaRestApi();
    return Object.values(this.positions).map(position => {
      // overwrite profits by ticker price from position; ticker prices are more fresh
      if (position.getEntry() && this.tickers[position.getSymbol()]) {
        const profit = position.isLong()
          ? (this.tickers[position.symbol].bid / position.entry - 1) * 100 // long profit
          : (position.entry / this.tickers[position.symbol].ask - 1) * 100; // short profit

        return Position.createProfitUpdate(position, profit);
      }

      return position;
    });
  }
```

and update updateOrder function to check if order.amout OR order.price were undefined instead of AND operator currently used.

This is certainly not the best method to overcome this but maybe this can help others.
I think it may be linked to #53

**Comment by Haehnchen** [comment] 2020-11-10 19:27
`syncPositionViaRestApi` is doing a forced API request, which should by design not done by the method itself, its called alot.

binance_futures (api+websocket) improved a lot since it launch, which is also reflected in the implementation here. i have no issues after a lot of fine tuning since month.

closing this for now.

**Closed by Haehnchen** 2020-11-10 19:27 UTC

**Comment by gelinger777** [comment] 2021-02-02 23:08
@Haehnchen  I have experienced a duplicate order on Cross Margin binance_margin too right now .

```
Webserver listening on: 0.0.0.0:8080
Trade module: warmup done; starting ticks
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
Order {
  id: 1520777842000,
  symbol: 'ADAUSDT',
  side: 'short',
  price: -0.43676,
  amount: -27.4,
  type: 'limit',
  options: { adjust_price: true, post_only: true } }
*((********************************************
Order created: [867408172,"binance_margin","ADAUSDT"]
{"message":"Binance Margin: order create error: [-3007,\"You have pending transcation, please try again later.\",{\"id\":579561115014,\"symbol\":\"ADAUSDT\",\"side\":\"short\",\"price\":-0.43562,\"amount\":27.4,\"type\":\"limit\",\"options\":{}},{\"symbol\":\"ADAUSDT\",\"side\":\"SELL\",\"quantity\":27.4,\"price\":0.43562,\"type\":\"LIMIT\",\"newClientOrderId\":579561115014,\"sideEffectType\":\"MARGIN_BUY\"}]","level":"error","timestamp":"2021-02-02T23:00:12.191Z"}
{"message":"OrderAdjust: Unknown order state: [{\"time\":\"2021-02-02T23:00:09.488Z\",\"exchange\":\"binance_margin\",\"symbol\":\"ADAUSDT\",\"state\":\"short\",\"options\":{},\"exchangeOrder\":{\"id\":867408172,\"symbol\":\"ADAUSDT\",\"status\":\"open\",\"price\":0.43676,\"amount\":27.4,\"retry\":false,\"ourId\":\"1520777842000\",\"side\":\"sell\",\"type\":\"limit\",\"createdAt\":\"2021-02-02T23:00:10.480Z\",\"updatedAt\":\"2021-02-02T23:00:10.794Z\",\"raw\":{\"symbol\":\"ADAUSDT\",\"orderId\":867408172,\"clientOrderId\":\"1520777842000\",\"transactTime\":1612306810480,\"price\":\"0.43676\",\"origQty\":\"27.4\",\"executedQty\":\"0\",\"cummulativeQuoteQty\":\"0\",\"status\":\"NEW\",\"timeInForce\":\"GTC\",\"type\":\"LIMIT\",\"side\":\"SELL\",\"fills\":[],\"marginBuyBorrowAsset\":\"ADA\",\"marginBuyBorrowAmount\":\"27.4\",\"isIsolated\":false},\"options\":{}},\"retries\":0,\"adjustedPrice\":true,\"cleared\":false,\"capital\":{\"type\":\"currency\",\"currency\":12}},null]","level":"error","timestamp":"2021-02-02T23:00:12.191Z"}
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
Order {
  id: 1361542464109,
  symbol: 'OMGUSDT',
  side: 'long',
  price: '3.94630000',
  amount: '3.04',
  type: 'limit',
  options: { adjust_price: true, post_only: true } }
*((********************************************
Order created: [349550082,"binance_margin","OMGUSDT"]
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
Order {
  id: 1389450180904,
  symbol: 'XLMUSDT',
  side: 'long',
  price: '0.33954000',
  amount: '64.7',
  type: 'limit',
  options: { adjust_price: true, post_only: true } }
*((********************************************
Order created: [613657464,"binance_margin","XLMUSDT"]
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
Order {
  id: 1602105375421,
  symbol: 'ADAUSDT',
  side: 'short',
  price: -0.43464,
  amount: -27.6,
  type: 'limit',
  options: { adjust_price: true, post_only: true } }
*((********************************************
Order created: [867409214,"binance_margin","ADAUSDT"]
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
Order {
  id: 1486921695200,
  symbol: 'OMGUSDT',
  side: 'long',
  price: '3.94300000',
  amount: '3.04',
  type: 'limit',
  options: { adjust_price: true, post_only: true } }
*((********************************************
Order created: [349550374,"binance_margin","OMGUSDT"]
{"message":"Binance Margin: order create error: [-3007,\"You have pending transcation, please try again later.\",{\"id\":1533105029697,\"symbol\":\"ADAUSDT\",\"side\":\"short\",\"price\":-0.43469,\"amount\":27.6,\"type\":\"limit\",\"options\":{}},{\"symbol\":\"ADAUSDT\",\"side\":\"SELL\",\"quantity\":27.6,\"price\":0.43469,\"type\":\"LIMIT\",\"newClientOrderId\":1533105029697,\"sideEffectType\":\"MARGIN_BUY\"}]","level":"error","timestamp":"2021-02-02T23:00:23.603Z"}
{"message":"OrderAdjust: Unknown order state: [{\"time\":\"2021-02-02T23:00:09.488Z\",\"exchange\":\"binance_margin\",\"symbol\":\"ADAUSDT\",\"state\":\"short\",\"options\":{},\"exchangeOrder\":{\"id\":867409214,\"symbol\":\"ADAUSDT\",\"status\":\"open\",\"price\":0.43464,\"amount\":27.6,\"retry\":false,\"ourId\":\"1602105375421\",\"side\":\"sell\",\"type\":\"limit\",\"createdAt\":\"2021-02-02T23:00:22.379Z\",\"updatedAt\":\"2021-02-02T23:00:22.635Z\",\"raw\":{\"symbol\":\"ADAUSDT\",\"orderId\":867409214,\"clientOrderId\":\"1602105375421\",\"transactTime\":1612306822379,\"price\":\"0.43464\",\"origQty\":\"27.6\",\"executedQty\":\"0\",\"cummulativeQuoteQty\":\"0\",\"status\":\"NEW\",\"timeInForce\":\"GTC\",\"type\":\"LIMIT\",\"side\":\"SELL\",\"fills\":[],\"marginBuyBorrowAsset\":\"ADA\",\"marginBuyBorrowAmount\":\"0.2\",\"isIsolated\":false},\"options\":{}},\"retries\":0,\"adjustedPrice\":true,\"cleared\":false,\"capital\":{\"type\":\"currency\",\"currency\":12}},null]","level":"error","timestamp":"2021-02-02T23:00:23.603Z"}
{"message":"OrderAdjust: Unknown order state: [{\"time\":\"2021-02-02T23:00:14.989Z\",\"exchange\":\"binance_margin\",\"symbol\":\"XLMUSDT\",\"state\":\"long\",\"options\":{},\"exchangeOrder\":{\"id\":613657483,\"symbol\":\"XLMUSDT\",\"status\":\"open\",\"price\":0.33956,\"amount\":64.7,\"retry\":false,\"ourId\":\"1091846932824\",\"side\":\"buy\",\"type\":\"limit\",\"createdAt\":\"2021-02-02T23:00:16.673Z\",\"updatedAt\":\"2021-02-02T23:00:16.799Z\",\"raw\":{\"symbol\":\"XLMUSDT\",\"orderId\":613657483,\"clientOrderId\":\"1091846932824\",\"transactTime\":1612306816673,\"price\":\"0.33956\",\"origQty\":\"64.7\",\"executedQty\":\"0\",\"cummulativeQuoteQty\":\"0\",\"status\":\"NEW\",\"timeInForce\":\"GTC\",\"type\":\"LIMIT\",\"side\":\"BUY\",\"fills\":[],\"isIsolated\":false},\"options\":{}},\"retries\":0,\"adjustedPrice\":true,\"cleared\":false,\"capital\":{\"type\":\"currency\",\"currency\":22}},{\"id\":613657692,\"symbol\":\"XLMUSDT\",\"status\":\"done\",\"price\":0.33974,\"amount\":0,\"retry\":false,\"ourId\":\"162953643878\",\"side\":\"buy\",\"type\":\"limit\",\"createdAt\":\"2021-02-02T23:00:27.030Z\",\"updatedAt\":\"2021-02-02T23:00:27.158Z\",\"raw\":{\"symbol\":\"XLMUSDT\",\"orderId\":613657692,\"clientOrderId\":\"162953643878\",\"transactTime\":1612306827030,\"price\":\"0.33974\",\"origQty\":\"64.7\",\"executedQty\":\"64.7\",\"cummulativeQuoteQty\":\"21.976649\",\"status\":\"FILLED\",\"timeInForce\":\"GTC\",\"type\":\"LIMIT\",\"side\":\"BUY\",\"fills\":[{\"price\":\"0.33967\",\"qty\":\"64.7\",\"commission\":\"0.0647\",\"commissionAsset\":\"XLM\"}],\"isIsolated\":false},\"options\":{}}]","level":"error","timestamp":"2021-02-02T23:00:27.158Z"}

``` 

Any ideas how to fix that?
