### ISSUE TITLE
Bot doest make trades

### ISSUE THREAD

**Issue by jojoosinga** [Haehnchen/crypto-trading-bot#83] opened 2019-11-09 09:09 UTC
Hi, I got the bot compiled on Linux and working API keys but the says it's trading but it's not is there something in the config. It's this for default
`y.forEach((pair) => {
    c.symbols.push({
        'symbol': pair,
        'periods': ['1m', '15m', '1h'],
        'exchange': 'bitmex',
        'state': 'watch',`

but i thought is has to be `y.forEach((pair) => {
    c.symbols.push({
        'symbol': pair,
        'periods': ['1m', '15m', '1h'],
        'exchange': 'bitmex',
        'state': 'trade',
`

**Comment by jojoosinga** [comment] 2019-11-09 19:19
and when i do change it it gets me this
`Ticker no found for + bitmexETH_USD
Ticker no found for + bitmexETH_USD
Ticker no found for + bitmexETH_USD
Ticker no found for + bitmexXBT_USD
Ticker no found for + bitmexXBT_USD
Ticker no found for + bitmexXBT_USD
Ticker no found for + bitmexETH_USD
Ticker no found for + bitmexETH_USD
Ticker no found for + bitmexETH_USD
Ticker no found for + bitmexXBT_USD
Ticker no found for + bitmexXBT_USD
Ticker no found for + bitmexXBT_USD
Ticker no found for + bitmexETH_USD
Ticker no found for + bitmexETH_USD
Ticker no found for + bitmexETH_USD
Ticker no found for + bitmexXBT_USD
Ticker no found for + bitmexXBT_USD
Ticker no found for + bitmexXBT_USD
Ticker no found for + bitmexETH_USD
Ticker no found for + bitmexETH_USD
Ticker no found for + bitmexETH_USD`

**Comment by hatzkel** [comment] 2019-11-10 20:31
Because those are not their ticker symbols. XBTUSD and ETHUSD no _ inbetween. Change them in the config.

**Comment by fidel1986** [comment] 2019-11-29 18:13
Duplicate of #27

**Comment by Haehnchen** [comment] 2020-11-10 19:15
trade is also support; to not get confused

**Closed by Haehnchen** 2020-11-10 19:15 UTC
