### ISSUE TITLE
run node index.js trade fail

### ISSUE THREAD

**Issue by beaquant** [Haehnchen/crypto-trading-bot#86] opened 2019-11-26 09:27 UTC
when run `node index.js trade`, it's fail
```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/mnt/e/github.com/crypto-trading-bot/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/mnt/e/github.com/crypto-trading-bot/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

don't know how to fix it

**Comment by hatzkel** [comment] 2019-11-26 13:12
When is this occuring? I suggest if this is your first time running this to use the docker and follow the simple instructions in the readme. It saves you the headache of dependency hell and errors caused by not having a proper development environment.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by beaquant** [comment] 2019-11-28 14:06
thanks a lot, it's work with docker.
but how to set proxy?

**Comment by beaquant** [comment] 2019-11-28 14:09
> When is this occuring? I suggest if this is your first time running this to use the docker and follow the simple instructions in the readme. It saves you the headache of dependency hell and errors caused by not having a proper development environment. Sent from ProtonMail mobile
> […](#)

## I follow the install structure to get the failure

> ### Install packages

```
➜ npm install --production
➜ npm run postinstall
```

Create instance file for pairs and changes

```
cp instance.js.dist instance.js
```

Provide a configuration with your exchange credentials

```
cp conf.json.dist conf.json
```

Create a new sqlite database use bot.sql scheme to create the tables
```
sqlite3 bot.db < bot.sql
```

Lets start it

```
node index.js trade
```

**Comment by hatzkel** [comment] 2019-12-14 15:02
Yes. You will encounter errors following the install instructions due to the dependencies this is why it is recommended to run docker when building anything these days unless you specifically set up a build environment in a VM with all the exact dependencies required to build the app.

**Comment by Haehnchen** [comment] 2020-11-10 18:46
local issues. closing

**Closed by Haehnchen** 2020-11-10 18:46 UTC
